### ISSUE TITLE
How to add mock for `/api/v0/pin/remote/service/ls` endpoint?

### ISSUE THREAD

**Issue by joewagner** [httptoolkit/mockipfs#2]
Hello 👋 
Thanks for creating this package! It seems to be exactly what my org needs to setup testing for a [package](https://github.com/tablelandnetwork/jeti) we are working on to help devs more easily integrate IPFS with a SQL database we are building. 

### This issue I'm having
One of the tests I've written makes a call to a method that does the following internally:
```
const ipfs = await IPFS.create(ipfsOptions);
const pinningServices = await ipfs.pin.remote.service.ls();
```
This results in my test erroring with the following message:
```
HTTPError: No rules were found matching this request.
This request was: POST request to http://localhost:8000/api/v0/pin/remote/service/ls with headers:
{
  "host": "localhost:8000",
  "connection": "keep-alive",
  "accept": "*/*",
  "accept-language": "*",
  "sec-fetch-mode": "cors",
  "user-agent": "undici",
  "accept-encoding": "gzip, deflate",
  "content-length": "0"
}

The configured rules are:
Match requests making POSTs for /api/v0/name/publish, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/name/resolve, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/resolve, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/pin/add, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/pin/rm, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/pin/ls, and then respond with status 200, headers {"cache-control":"no-cache","connection":"close","date":"Fri, 19 May 2023 17:51:47 GMT","content-type":"application/json; charset=utf-8","transfer-encoding":"chunked","x-chunked-output":"1"}, always (seen 0).
Match requests making POSTs for /api/v0/add, and then respond using provided callback, always (seen 0).
Match requests making POSTs for /api/v0/cat, and then time out (never respond), always (seen 0).


You can fix this by adding a rule to match this request, for example:
mockServer.forPost("/api/v0/pin/remote/service/ls").thenReply(200, "your response");
```

I walked through this codebase a little bit, but I'm struggling to find the correct way to add an endpoint to the mockttp server for the "/api/v0/pin/remote/service/ls" endpoint.

### What I've tried
Everything I've tried results in the same error, as described above.

I first tried using this package's `forPinLs` method as follows:
```
const mockNode = MockIPFS.getLocal();
mockNode.forPinLs().thenReturn([{type: "foo", cid: "bafy"}]);
```

The error message seems to come from the "mockttp" package, so I tried accessing it directly via the following: 
```
const mockNode = MockIPFS.getLocal();
mockNode.mockttpServer.addRequestRule({
    priority: Mockttp.RulePriority.DEFAULT,
    matchers: [
        new Mockttp.matchers.SimplePathMatcher("/api/v0/pin/remote/service/ls")
    ],
    completionChecker: new Mockttp.completionCheckers.Always(),
    handler: new Mockttp.requestHandlers.SimpleHandler(200, "", "foozbaz")
});
```

---------------------

Thank you ahead of time to anyone who has any idea how I can proceed.  If I find a solution I'll post it here.

**Comment by pimterry** [comment]
Hi @joewagner! This isn't supported yet, but it certainly makes sense so I'd happily accept a PR, and it should be easy to add if you're interested.

To do so, you'll need to:

* Make a builder for remote ls rules (something just like https://github.com/httptoolkit/mockipfs/blob/main/src/pinning/pin-ls-rule-builder.ts) that takes the arguments for the rule, and defines what the HTTP response should look like. It's probably very similar to the normal Ls response, but this would need some quick testing with a real request to confirm. It's probably easiest to check this by using [HTTP Toolkit](https://httptoolkit.com/), sending a real valid request there, and then looking at the format of the raw response you get back.
* Add a default fallback rule for the endpoint within the pinning mock [here](https://github.com/httptoolkit/mockipfs/blob/7496654f593b5cb937cd1a6d3fd82f0458085001/src/pinning/pinning-mock.ts#L23), so it does something sensible when no rules are specified (again probably the same as normal Ls, i.e. just return an empty list)
* Add a `addRemotePinLs` method to the pinning mock, just like [the ls one](https://github.com/httptoolkit/mockipfs/blob/7496654f593b5cb937cd1a6d3fd82f0458085001/src/pinning/pinning-mock.ts#L85-L94) but with the different path
* Glue it all together with an `node.forRemotePinLs()` method just like [forPinLs](https://github.com/httptoolkit/mockipfs/blob/7496654f593b5cb937cd1a6d3fd82f0458085001/src/mockipfs-node.ts#L224-L231), which creates the builder and passes it the `addRemotePinLs` as a callback.
* Create tests to check it, probably very similar to [these ones](https://github.com/httptoolkit/mockipfs/blob/7496654f593b5cb937cd1a6d3fd82f0458085001/test/integration/pin.spec.ts#L144-L214).

Once that's in place and working, you'll be able to just use `mockNode.forRemotePinLs().thenReturn(...)` to do your mocking.

Does that make sense? Happy to provide pointers if there's anything that trips you up there.

**Comment by joewagner** [comment]
@pimterry That sounds great!  I'll start working on a PR later today
